#!/bin/bash

if (( $# == 0 )); then
  echo "usage: $0 [username@]hostname [...]"
  exit 1
fi
cd $(dirname $0)
for h in "$@"; do
  echo pushing to $h
  rsync -av --exclude .git --exclude "*~" --exclude push-home . $h:
  [ -r ~/.nestrc ] && rsync ~/.nestrc $h:
  if true || [ ssh $h test -r /bin/zsh ]; then
    rsync -av --exclude .git --exclude "*~" --delete ~/.oh-my-zsh $h:
  fi
done
