# for interactive shells

# make option and trap changes local to functions
setopt LOCAL_OPTIONS LOCAL_TRAPS

# when there's an ambiguous completion, offer the first one right away
#setopt MENU_COMPLETE

# don't beep on ambiguous completion
unsetopt LIST_BEEP

# Treat the #, ~ and ^ characters as part of patterns for filename generation, etc.
setopt EXTENDED_GLOB

# Long history.
HISTSIZE=60
# Normally "history" is "fc -l", which only shows the last 16 entries.
# We force the entries to start at 1 (and end at the current entry).
alias history='fc -l 1'

[ -d /usr/local/share/zsh-completions ] && fpath=(/usr/local/share/zsh-completions $fpath)
# remove redundant entries in path, cdpath, etc.
typeset -U path cdpath manpath fpath mailpath

# basic aliases
alias vi=vim

# bash-ism
bindkey '^R' history-incremental-search-backward

# expand history when space is typed
bindkey ' ' magic-space

# other useful things to autoload
autoload zmv	# better move

# super completion.  unfortunately this takes a while to load
# disabled -- it was sometimes taking too long to complete, too
# autoload compinit
# compinit

# when completing after a CD-type command, complete only directories
# or links to directories:
compctl -/ cd chdir dirs pushd

# environment variables
export EDITOR=vim
export VISUAL=vim

#export VIMINIT="source $HOME/vimfiles/vimrc"
#export GVIMINIT="source $HOME/vimfiles/gvimrc"

set -o emacs

[ -r ~/.nestrc ] && . ~/.nestrc

# For pj ("project jump") plugin
[ -d ~/projects ] && PROJECT_PATHS=(~/projects)

# For ssh-agent plugin
ssh_key_names=($(egrep -l 'PRIVATE KEY' ~/.ssh/id_* 2> /dev/null | sed -e 's,.*/,,' | tr '\n' ' '))
if [ -n "$ssh_key_names" ]; then
  zstyle :omz:plugins:ssh-agent agent-forwarding yes
  zstyle :omz:plugins:ssh-agent identities $ssh_key_names
fi
unset ssh_key_names
